#! /usr/bin/sh

simulate-browser --regex 'play\.podtrac\.com/npr-2/ondemand\.npr\.org' ondemand.npr.org '\.mp3\?orgId=.*?"' '.mp3"' https://www.kuow.org/feeds/podcasts/all-things-considered/podcasts/rss.xml

