#! /bin/sh

# Removes the subscribe link from each article
simulate-browser --regex '<[aA] href="https://nebraskaexaminer\.com/subscribe".*?>(?:.|\n)*?</[aA]>' '' 'https://nebraskaexaminer.com/feed'

# vim:set filetype=sh et:

